config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :users, only: [:show]
  resources :items, only: [:create, :destroy, :update]

  root to: 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  
    belongs_to :user
    require 'date'
    
    default_scope { order('end_date ASC') }
    
    validates :body, length: { minimum: 4 }, presence: true
    validates :user, presence: true
    # validates :lifespan, numericality: { only_integer: true, greater_than: 0, less_than: 100 }
    

    def created_at
      created_at ||= Time.zone.now 
    end
    
    
    def lifespan=(days)
        self.end_date = self.created_at + days.to_i.days
    end
    
    def lifespan
      if self.end_date.present?
        (self.end_date - self.created_at)/1.day
      end
    end
    
    def days_left
      (self.end_date.to_date - Date.today).round(0)
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :items, dependent: :destroy
  
  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
     
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
   
    #attempt to make flash messages work with ajax
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
  #Allows user to add and edit name, must be here because rails 4 has moved this to controller, so cannot be in user model
     private
     
     def user_not_authorized
       flash[:alert] = "Oops!  You don't have permission to do this."
       redirect_to root_path
     end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # include ItemsHelper
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      flash[:notice] = "Item was saved. You have #{@item.lifespan.round(0)} days to complete it!"
      redirect_to [current_user]
      #will need to update this to use ajax
    else
      flash[:error]
      # = "There was an error saving the item.  Please try again."
      redirect_to [current_user]
    end
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
  end
  
  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
      flash[:notice] = "#{ success_message }"
    else 
      flash[:error] = "There was an error marking the task complete. Are you sure you finished it?"
    end
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:body, :lifespan, :public)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        authorize @user
        @items = policy_scope(@user.items)
        @item = Item.new
        # render json: @user
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/items_helper.rb
module ItemsHelper
    def success_message
      complete = [
        "Great job!",
        "Give yourself a high five!",
        "Task marked as complete!",
        "You did it!",
        "Congrats!",
        "Good work!"
        ]
      quotes = [
  
      "'What you do today can improve all your tomorrows.' --Ralph Marston",
      
      "'Don't watch the clock; do what it does. Keep going.' --Sam Levenson",
      
      "'Life is 10% what happens to you and 90% how you react to it.' --Charles R. Swindoll",
      
      "'Accept the challenges so that you can feel the exhilaration of victory.' --George S. Patton",
      
      "'It does not matter how slowly you go as long as you do not stop.' --Confucius",
      
      "'You are never too old to set another goal or to dream a new dream.' --C. S. Lewis",
      
      "'Always do your best. What you plant now, you will harvest later.' --Og Mandino",
      
      "'The secret of getting ahead is getting started.' --Mark Twain",
      
      "'Start where you are. Use what you have. Do what you can.' --Arthur Ashe",
      
      "'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.' --Thomas A. Edison",
      
      "'The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.' -Confucius",
      
      "'Keep your eyes on the stars, and your feet on the ground.' --Theodore Roosevelt",
      
      "'Knowing is not enough; we must apply. Willing is not enough; we must do.' --Johann Wolfgang von Goethe"
      ]
    "#{complete.sample}  #{quotes.sample}"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>

    <div class='form-group'>
        <%= f.label :item %></br>
        <%= f.text_area :body %>
    </div>
    <p><b>How many days would you like to complete this task?  We recommend 7.</b><p>
    <div class="form-group">
        <%= f.text_field :lifespan %>
    </div>
    <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
            <%= f.check_box :public %> Public?
        <% end %>
    </div>
    <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/items/_item.html.erb
    
    <%= content_tag :tr, id: "item-#{item.id}" do %>
            <td><%= item.body %></td>
        <td class="text-center"><%= item.days_left %></td>
        <td class="text-center"><%= link_to "", item, method: :delete, class: 'glyphicon glyphicon-ok', remote: true %></td>
    </tr>
    <% end %>
    
    

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
    $('#item-' + <%= @item.id %>).hide();
    <%= render partial: 'shared/flashes', formats: [:js] %>
    <% else %>
    $('#item-' + <%= @item.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div class="container" id="bootstrap-overrides">
    <%= render partial: 'shared/flashes' %>
       
       <div class="pull-right user-info">
            <% if current_user %>
                Hello <%= link_to (current_user.name || current_user.email), current_user %>!
                <%= link_to edit_user_registration_path(current_user), class: 'btn btn-primary btn-sm' do %>
                    <span class="glyphicon glyphicon-user"></span>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
                    <span class="glyphicon glyphicon-log-out"></span>
                <% end %>
            <% else %>
                <% link_to "Sign In", root_path %>
                <% link_to "Sign Up", root_path %>
            <% end %>
        </div>
        
    <%= yield %>

</div>
     
        
</body>
</html>

app/views/shared/_flashes.html.erb
  <div class="flashes">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

app/views/shared/_flashes.js.erb
$('.flashes').replaceWith('<%= escape_javascript(render partial: 'shared/flashes', formats: [:html]) %>');

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
<h1> <%= @user.name %> </h1>
        <table class="table table-bordered table-striped table-responsive" style="opacity=1">
            <tr class>
                <th class="text-center">Item</th>
                <th class="text-center">Days Left</th>
                <th class="text-center">Complete</th>
            </tr>
            <%= render @items %>
        </table>

<%= render "items/form", locals: { item: @item } %>
</div>
<div class="col-md-2"></div>
</row>

app/views/welcome/index.html.erb
<div class="container">
    <div class="jumbotron" id="jumbo">
    <h1 id="header">BlocItOff</h1>
        <p>A self destructing to-do list.  It gives up on you, so you don't have to give up on yourself.</p>
    </div>

<div class= "row">
  <div class="col-md-2">
    
    <h2>Sign In</h2>
    
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>
  
      <% if devise_mapping.rememberable? -%>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
      </div>
      <% end %>

      <div class="actions">
        <%= f.submit "Log in" %>
      </div>
    <% end %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  </div>

  <div class="col-md-8">
    <div class="img text-center">
      <img id="img" src="http://i.imgur.com/2yxcY0nl.jpg">
    </div>
  </div>

  <div class="col-md-2">
    <h2>Sign Up</h2>

    <%= form_for(:user, :url => session_path(:user)) do |f| %>
     <%= devise_error_messages! %>
  
      <div class="field">
        <%= f.label :name %><br/>
        <%= f.text_field :name, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div></br>

      <div class="actions">
        <%= f.submit "Sign up" %>
      </div>
    <% end %>

  </div>

</div>